# Site Specific Configuration
name: SkillJot
description: Your Skills, Your Story, Your Success!
url: https://www.skilljot.com
author: Alen Horvat
timezone: Europe/Ljubljana
timezone_short: CET

# Keywords
keywords: ['skills', 'work', 'education', 'experience', 'easy', verifiable]

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

