# Site Specific Configuration
name: SkillJot
url: https://www.skilljot.com
author: Alen Horvat
timezone: Europe/Ljubljana
timezone_short: CET

# Keywords

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-seo-tag

